### ISSUE TITLE
0.9.0 reporting connected dependencies via xref

### ISSUE THREAD

**Issue by raphaklaus** [sasa1977/boundary#44]
Hello! I am trying to reduce the number of transitive deps in my application using the insightful `mix xref graph --label compile-connected` command from Elixir's master. Doing so I noticed some unexpected output while running the tool. That doesn't happen in version 0.8.0.

How to reproduce:

```elixir
defmodule MyNewApp do
  use Boundary, deps: [Schema]
end
```

```elixir
defmodule MyNewAppWeb do
  use Boundary, deps: [MyNewApp]

  # All the rest of Web things here
 end
```

```elixir
defmodule Schema do
  use Boundary,
    deps: [],
    exports: []
end
```

And run the xref command aforementioned. The output will list some of the modules being transitive deps of the other.
Let me know if you are not able to simulate it and I can get you a demo repo (I will just take some days to)

**Comment by sasa1977** [comment]
Before 0.9.0 boundary introduced no dependencies between the modules. However, this required some dynamic code evaluation and trickery, and caused compile-time exceptions (see #41), so I moved to a simpler approach which introduces runtime, but not compile-time dependencies. Now, runtime deps might still cause recompilation if they are a part of a transitive chain, as explained [here](https://dashbit.co/blog/speeding-up-re-compilation-of-elixir-projects) (last paragraph in "Types of dependencies"), so perhaps this is what you're experiencing. Reading this report I can't exactly see what's happening vs what's expected. A small example project explaining and demonstrating the problem would be helpful.

**Comment by raphaklaus** [comment]
Demo repo: https://github.com/raphaklaus/boundary_lib_issue

It has version 0.9.0 by default. Using Elixir 1.13 or master, run `mix xref graph --label compile-connected --fail-above 10` you will see some output. Downgrade the lib to version 0.8.0, run the same xref command, no compile-connected reported.

**Comment by jdewar** [comment]
0.9.0
```
Generated boundary_lib_issue app
lib/boundary_lib_issue_web/controllers/page_controller.ex
└── lib/boundary_lib_issue_web.ex (compile)
lib/boundary_lib_issue_web/router.ex
└── lib/boundary_lib_issue_web.ex (compile)
lib/boundary_lib_issue_web/views/error_view.ex
└── lib/boundary_lib_issue_web.ex (compile)
lib/boundary_lib_issue_web/views/layout_view.ex
└── lib/boundary_lib_issue_web.ex (compile)
lib/boundary_lib_issue_web/views/page_view.ex
└── lib/boundary_lib_issue_web.ex (compile)
```

0.8.0
```
Generated boundary_lib_issue app
```

**Comment by sasa1977** [comment]
Thank you for reporting. This is a consequence of the recent internal changes in the latest version. Previously, I did some hacky mangling to avoid any dependencies. However, that caused compile-time exceptions (see #41). The latest version introduces a runtime dependency. So when in the module `Foo` you write `use Boundary, deps: [Bar]`, `Foo` will have a runtime dependency on `Bar`.

This is itself not a problem. However, the code generated by the Phoenix generator introduces compile-time dependencies. For example:

- `use BoundaryLibIssueWeb, :controller` adds a compile-time dependency between `BoundaryLibIssueWeb.PageController` and `BoundaryLibIssueWeb`. Furthemore, the code injected into the controller module does `use Phoenix.Controller, namespace: BoundaryLibIssueWeb` which creates another compile-time dependency between the controller and the web module.

As a result, the controller module depends on `BoundaryLibIssueWeb` at compile-time (this is not boundary related), while `BoundaryLibIssueWeb` depends on `BoundaryLibIssue` at runtime (because of `use Boundary, deps: [BoundaryLibIssue]`). Consequently, a change in `BoundaryLibIssue` will require recompilation of `BoundaryLibIssueWeb`, and since controllers and views are compile-time depending on it, those modules will have to be recompiled too.

The root cause of these dependencies is IMO the generated Phoenix structure which creates compile-time dependencies between web modules (views, controllers, etc) and the root web module. You could remove these dependencies by:

1. Having `use MyWeb.Controller`, `use MyWeb.View`, etc instead of `use MyWeb, :controller`. TBH I find this approach more straightforward than what Phoenix generates.
2. You'd also have to get rid of the `namespace: MyWeb` option in views/controllers. I'm not sure what are the implications of that without trying it out.

With those changes, the transitive compile-time dependencies from `BoundaryLibIssueWeb` modules to `BoundaryLibIssue` will be removed.

I'll consider moving back to the hackiness I did previously, which would avoid introducing any dependencies between modules when using boundary. I'd obviously have to do some minor changes to avoid the crash in #41, but I think it should be possible. The downside is that the solution is more complicated, hacky, and much harder to understand.

**Comment by sasa1977** [comment]
Got some tips by José on how to avoid adding runtime dependency. I pushed the fix to master, and trying it with your example repo the problem seems fixed. If it still happens in your project let me know.
