### ISSUE TITLE
Huge compilation slowdown with large project

### ISSUE THREAD

**Issue by hoyon** [sasa1977/boundary#49]
Hi, we're investigating integrating boundary into our project with ~1300 modules and we're seeing a huge compilation cost with our initial spike.

Before, running `mix compile --force` takes around 30s while with boundary it takes it up to 2 minutes. (This is on an M1 macbook pro). Incremental compiles are also much slower.

What I'm wondering is:
- To get us started we've disabled checks for many boundaries with `check: [in: false, out: false]`. Would reducing our code coupling and thus enabling boundary fully improve compile times?
- Are there any areas where you can see opportunity for performance improvements? I'm happy to spend some time working on this if you think there are gains to be made.

Sadly right now the compile speed is preventing us from using boundary in our project.

**Comment by sasa1977** [comment]
Yeah, while I included some upfront optimizations I didn't really spend a lot of effort in optimizing. Boundary has been used in practice in smaller projects, but never on a larger one.

Basically, this requires further analysis. We first need a large test project. Perhaps something synthetic could be generated relatively quickly. Then we need to find out where the time is spent. Roughly speaking, there are three main phases: 

- data collection (driven by the [compilation tracer](https://github.com/sasa1977/boundary/blob/master/lib/boundary/mix/tasks/compile/boundary.ex))
- [view building](https://github.com/sasa1977/boundary/blob/master/lib/boundary/mix/tasks/compile/boundary.ex#L171-L175)
- [checking](https://github.com/sasa1977/boundary/blob/master/lib%2Fboundary%2Fchecker.ex)

While there are some other intermediate step, my first guess would be that the bottleneck is in some of those. A quick first check would be to drop [this line](https://github.com/sasa1977/boundary/blob/master/lib/boundary/mix/tasks/compile/boundary.ex#L90) and observe the duration. This would allow us to check the performance penalty of the compilation tracer. 

Likewise, we could temporarily comment out checking, and measure. The main idea here is to hopefully find one phase which is the slowest. If we're lucky, we can proceed to analyze it deeper. 

Based on your report I'm hoping that the data collection phase is fast enough (since incremental compiles are much slower), so my bet is either on the view builder or the checker.

I can look into this when I find the time, but I can't say when will that be, probably not soon. So if you're willing to investigate, I'd be happy to assist.

**Comment by randycoulman** [comment]
I performed this test on our codebase, which is not as large as @hoyon's. Without the boundary compiler, our app takes ~15s to compile (`MIX_ENV=test mix compile --force`). With it fully in effect, it takes ~43s. With the `after_compile` line commented out, it takes ~41s.

Of note, we typically get a few `(it's taking more than 10s)` warnings on various files during compilation.

So, for our app, it looks like the compilation tracer is where to focus. I haven't yet had time to dig in to narrow it down further, but this might give someone else a place to start.

**Comment by sasa1977** [comment]
Thank you for doing this! I must confess I didn't expect such results, but this is another demonstration that measuring is much better than guessing :-)

I did a quick experiment on a much smaller project, where the full compilation took about 6s without boundary, and about 8s with boundary. As it turns out, in this case most of the time has been spent [repeatedly calling :code.which](https://github.com/sasa1977/boundary/blob/13d0c9aa6982b4e7ff8b4dcc4b4c9b5280eac55d/lib/boundary/mix/tasks/compile/boundary.ex#L158).

I tried caching this info (since we repeatedly invoke this function against a fairly small set of modules), and this reduced the compilation time to about 6.3s. There's probably more room for improvements, but this seems like a promising start.

This change is available in the [improve-perf](https://github.com/sasa1977/boundary/tree/improve-perf) branch. Could you please give it a try and report back?

**Comment by sasa1977** [comment]
Looking into this further, I found out about [:erlang.pre_loaded](https://www.erlang.org/doc/man/erlang.html#pre_loaded-0), which makes things even simpler and faster. I pushed the change to the same branch.

**Comment by randycoulman** [comment]
Wow, that makes a huge difference! The compile time on our app dropped to ~17s using this branch.

**Comment by sasa1977** [comment]
Great news, thanks for testing! I'd say this is a significant gain, so I'll merge this later today and push a patch release. 

There's obviously some room for improvements, since according to your report the after-tracer phase introduces a 2s penalty, but we can analyze this separately. Could you perhaps share some numbers about the project size (e.g. LOC count, number of modules, and number of boundaries)?

@hoyon I'd also love to hear your report if possible :-)

**Comment by randycoulman** [comment]
Rough numbers, counting only `*.ex` files: ~25KLOC, ~425 modules, ~70 boundaries (including sub-boundaries).

**Comment by hoyon** [comment]
Thanks a lot for this @sasa1977! Compile times are now around 34s with boundary enabled down from over 2 minutes as per my original post.

For some rough numbers we've got ~80KLOC and ~1300 modules.

**Comment by sasa1977** [comment]
This is now published to hex, version 0.9.2.

**Comment by juanperi** [comment]
hey, just chiming in because the results of the upgrade are insane
```
#old boundary 0.8.0
mix compile --force  492.56s user 155.36s system 306% cpu 3:31.09 total
# new boundary 0.9.2
mix compile --force  308.02s user 40.10s system 422% cpu 1:22.33 total
```

Thank you all for this!!!

**Comment by sasa1977** [comment]
I'm going to leave this issue open, because I feel there's more room for improvement, but this needs to be investigated further. I'm short on time, but in case anyone wants to help, a good first step would be generating a synthetic medium sized test project, or perhaps even better, a test-project generator which takes size as input parameter (e.g. number of modules), and then observing what's the overhead of checking boundaries, especially when nothing has to be recompiled.

**Comment by PragTob** [comment]
👋 

As a data point here are the compilation time of a bigger project compiling ~5200 files. The boundary setup right now is very rudimentary (8 high level applications, 2 with check: in: false, no sub domains) but I think it gives a good impression of very basic overhead - it's **suprisingly fast/little overhead**.

System:

```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Number of Available Cores: 8
Available memory: 16 GB
Elixir 1.14.3
Erlang 25.2
```

latest boundary, 0.9.4 I believe.

Benchmark:

```
➜  git:(minimum-boundary) ✗ hyperfine --warmup 1 'COMPILE_BOUNDARY=true mix compile --force' 'mix compile --force'
Benchmark 1: COMPILE_BOUNDARY=true mix compile --force
  Time (mean ± σ):     252.455 s ±  1.870 s    [User: 1128.863 s, System: 171.586 s]
  Range (min … max):   249.013 s … 254.769 s    10 runs

Benchmark 2: mix compile --force
  Time (mean ± σ):     245.655 s ±  5.813 s    [User: 1069.618 s, System: 145.878 s]
  Range (min … max):   237.535 s … 254.594 s    10 runs

Summary
  'mix compile --force' ran
    1.03 ± 0.03 times faster than 'COMPILE_BOUNDARY=true mix compile --force'
```

I'd call that negligible :)

@sasa1977 While I understand keeping it open, the title is scary sounding and I remember it gave me pause when I considered adding boundary for the first time ~last summer (as in: damn, we probably can't use this!). Reading the issue it turned out to be a non issue. I'd suggest to close the issue and maybe open a new one to just "further improve compile times/reduce overhead" or something :)

**Comment by sasa1977** [comment]
Thanks for sharing the numbers, this looks good indeed. Yeah, I agree. Let's close this issue until someone reports the problem again.
